### ISSUE TITLE
Twitter Container is Failing to Contain Tracking Links to Twitter

### ISSUE THREAD

**Issue by HURSSGH** [v1shwa/contain-twitter#1]
Hi,

I have yet to see a website where twitter container contains tracking links tied to Twitter Buttons.

FB Container contains these buttons, so I would think Twitter Container should also contain Twitter buttons. (Yes, there are bugs in FB Container re this issue, and I have reported them.)

Here is one example, this from the BBC. I see the same issue across most/all sites that have the Twitter button. So, I am just providing you this as an example.

Webpage:
`https://www.bbc.com/news/disability-49584591`

Button is at "Share this story" at the end of the article. The link which should be blocked (because it provides Twitter with tracking information) is as follows:
`https://twitter.com/intent/tweet?text=BBC%20News%20-%20Spikes%20-%20and%20other%20ways%20disabled%20people%20combat%20unwanted%20touching&url=https%3A%2F%2Fwww.bbc.com%2Fnews%2Fdisability-49584591`

Note that on this page, FB Container blocks FB proper, but fails to block FB messenger.

Thanks for the great effort! I hope you can resolve this problem as it is a serious defect in your efforts to containerize apps and prevent tracking.

**Comment by v1shwa** [comment]
Hey @HURSSGH , Thanks for creating the issue.

Even though it doesn't block the **Tweet** button on the site, it does not allow any network calls to twitter from other websites. So, unless you click the **Tweet** button on a website, twitter won't be able to track you. Even then, I believe it'd just get the referrer's url

Twitter container was created as simple & light-weight addon with a purpose to block twitter _automatically_ tracking you from the websites you visit, which seems to be working fine.

I agree that, it'd be nice to have a blocking note like FB container & I'll definitely look into sometime in the future or if you can send in a PR, I'm more than happy to merge it.

Thank you!
