### ISSUE TITLE
X redirecting to Twitter domain

### ISSUE THREAD

**Issue by osmano807** [v1shwa/contain-twitter#15]
I saw https://github.com/v1shwa/contain-twitter/commit/96060eb09a18d7481032a7324cd766126214883d as removing `twitter.com` domains, but even if I try to open `x.com` it redirects me to `twitter.com`, and with the extension installed all links loose the URL path on this redirect. Reverting to https://addons.mozilla.org/firefox/downloads/file/1043666/twitter_container-1.3.1.xpi at least doesn't loose the path redirect that `x.com` does and links work again.

Is this redirect some A/B testing from Twitter?

**Comment by DraconicNEO** [comment]
@v1shwa Why would you remove all the twitter domains from the extension if they are still currently in use? This change broke the whole addon. I hope this wasn't intentional and was just a mistake.

**Comment by v1shwa** [comment]
@osmano807 @DraconicNEO Thank you both for sharing your thoughts. My apologies for the oversight. I have just released a new version with this issue fixed. Can I request you to please update your add-ons and give it shot once again. 

I will keep this thread open just in case if you still face any issues.

**Comment by osmano807** [comment]
Thanks for the rapid response, updated to 1.3.3 and it seems to be working correctly both on twitter.com and x.com.

Alas, today `x.com` isn't redirecting to `twitter.com`, so I guess there's still some weirdness from X side.

**Comment by v1shwa** [comment]
@osmano807  Thank you confirming.

Yes, I did notice the same weirdness, it keeps switching between both the domains.

**Comment by DraconicNEO** [comment]
> Thanks for the rapid response, updated to 1.3.3 and it seems to be working correctly both on twitter.com and x.com.
> 
> Alas, today `x.com` isn't redirecting to `twitter.com`, so I guess there's still some weirdness from X side.

It's weird though because when I downgrade it stops happening, seems like it's definately update related.

**Comment by DraconicNEO** [comment]
> @osmano807 @DraconicNEO Thank you both for sharing your thoughts. My apologies for the oversight. I have just released a new version with this issue fixed. Can I request you to please update your add-ons and give it shot once again.
> 
> I will keep this thread open just in case if you still face any issues.

It works now but still randomly redirects to X
