### ISSUE TITLE
[Feature request] Option to use separate container on Tweetdeck

### ISSUE THREAD

**Issue by mben42** [v1shwa/contain-twitter#3]
Hello,

Is it possible to add an option to have Tweetdeck (tweetdeck.twitter.com) in another container than Twitter's one? It would be a good "fix" to the problem with the new Twitter interface that allows to use several accounts, but switches account used on Tweetdeck at the same time.

Thanks in advance,

**Comment by v1shwa** [comment]
If we remove tweetdeck from twitter container, you won't be able login to tweetdeck ever as this extension would block all the twitter HTTP calls outside the Twitter container.
