### ISSUE TITLE
Add x.com to twitter domains

### ISSUE THREAD

**Issue by vyv03354** [v1shwa/contain-twitter#9]
For obvious reasons.

**Comment by ShubhamVerma1811** [comment]
hi @v1shwa,good day!

With today's twitter changes these changes are needed. I noticed PR #11 got the changes along with formatting changes.

Would that be merged anytime in the future? or I can raise a PR with minimal changes.

**Comment by v1shwa** [comment]
Thanks @ShubhamVerma1811 , that is merged. thank you.
